### ISSUE TITLE
IBM IDs that need access. 

### ISSUE THREAD

**Issue by aaronmcohen** [EnterpriseDB/edb-k8s-doc#30]
**If user has Quay.io account please provide username**
username: 
- zurilawrence
- zacharygleason
- ursulazhou
- jtruskow
- ebb02fb
- hdaisuke
- yuichi
- m1miyaza_ibm
- wksops
- iryo

**Comment by aaronmcohen** [comment]
2 additional:
- mwakao
- vwjew

**Comment by taylorgrahamedb** [comment]
Thank you! Also done!
