### ISSUE TITLE
EDB repo access request

### ISSUE THREAD

**Issue by kotaroyoshino** [EnterpriseDB/edb-k8s-doc#32]
**If user has Quay.io account please provide username**
username: kotaro_yoshino

**If user has no Quay.io account provide email**
Email: kotaro.yoshino@enterprisedb.com

** Fill out client info **
Name: Kotaro Yoshino
Company: Enterprise Widgets

**Comment by taylorgrahamedb** [comment]
You already have a Quay account. Please check email

**Comment by kotaroyoshino** [comment]
Hi Graham,
Yes, I already have my quay account.
Now, I can login quay but I don't have edb repos in quay account.
So let me give you my user name below.

kotaro_yoshino

Thanks,
