### ISSUE TITLE
Request EDB quay repository access

### ISSUE THREAD

**Issue by vivek-k-thakur** [EnterpriseDB/edb-k8s-doc#34]
**If user has Quay.io account please provide username**
username: vivek_k_thakur

**If user has no Quay.io account provide email**
Email: vivek.k.thakur@enterprisedb.com

** Fill out client info **
Name: Vivek Kumar
Company: EnterpriseDB

**Comment by taylorgrahamedb** [comment]
added! please be on the look out for a email from Quay
