### ISSUE TITLE
Gap while following the documentation guided setup

### ISSUE THREAD

**Issue by JanKarremans** [EnterpriseDB/edb-k8s-doc#36]
I am following the steps to get the containers set up.
The documentation reads:

run: kubectl apply -f setup/storage-class-gce-pd.yaml

It does not state where and how to get it, as it jumps straight from "get access to Quai.io" to this point.

It should state where to find the "setup" folder and how to sync it locally.

**Comment by kelpoole** [comment]
@JanKarremans please include a link to the document in question or that the feedback is about - and possibly even how you got there to help us understand the "gap" better

**Comment by JanKarremans** [comment]
Used the readme on https://github.com/EnterpriseDB/edb-k8s-doc

And started with the getting started, as that seemed the right place to get started.

Note, I had clicked around a little already to get through Docker (to get that setup) and now got to k8s-CLI and ran aground. I went back to the getting started and noticed there was a kubectl apply -f setup/storage-class-gce-pd.yaml call already, but was not able to quickly find the setup/storage-class-gce-pd.yaml.

--> Note: I am very good at being dumb like that ;-)

**Comment by kelpoole** [comment]
ok so you are reading the readme.md in the main directory of the repo and it reference a setup folder with a file but it's unclear that it's a folder in the repo (and level) where you currently are?  is there a suggestion of how it could be clearer?  were you expecting full path?

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by JanKarremans** [comment]
I was at least expecting to find further instructions on where to find the repository with the files or, some kind of link to a more verbose description on where and how to get the files (suited for someone (a lot) less experienced in working with these repo's).
I come in blank and step halfway into a story where, if you have the access / experience, all is clear. Not so much for a newbee.

**Comment by kelpoole** [comment]
I'm going to close this issue for now.  If we hear similar complaints from others we will address
