### ISSUE TITLE
Request to access edb container repo

### ISSUE THREAD

**Issue by ruckmangathan** [EnterpriseDB/edb-k8s-doc#37]
**If user has no Quay.io account provide email**
Email: ruckmangathan.rajamanickam@anz.com

** Fill out client info **
Name: Ruckmangathan Rajamanickam
Company: ANZ

**Comment by taylorgrahamedb** [comment]
User: ruckmangathan.rajamanickam@anz.com has been added to EDB Qauy.io registry. You will be getting a email from Qauy.Io for access info. Any issues please let your sales engineer know. Thank you!
