### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by BobbehUK** [EnterpriseDB/edb-k8s-doc#38]
**If user has Quay.io account please provide username**
username: robert_pogmore

**If user has no Quay.io account provide email**
Email: robert.pogmore@enterprisedb.com

** EDB Sales Engineer for Account **
Name: Rob Pogmore

** Fill out client info **
Name: Rob Pogmore
Company: EnterpriseDB

**Comment by taylorgrahamedb** [comment]
done!
