### ISSUE TITLE
Need access 

### ISSUE THREAD

**Issue by amandeep-singhcs** [EnterpriseDB/edb-k8s-doc#39]
**If user has Quay.io account please provide username**
username: amandeep.singh

**If user has no Quay.io account provide email**
Email: amandeep.singh@enterprisedb.com

** EDB Engineer for Account **
Name: Amandeep Singh 

** Fill out client info **
Name: Amandeep Singh 
Company: EDB

**Comment by taylorgrahamedb** [comment]
Sent: you should have a email from Quay.io
