### ISSUE TITLE
Need access to quay.io registry to install/test EDB containers

### ISSUE THREAD

**Issue by snarain16** [EnterpriseDB/edb-k8s-doc#44]
**If user has Quay.io account please provide username**
username:  snarain

**If user has no Quay.io account provide email**
Email: sunil.narain@enterprisedb.com

** EDB Sales Engineer for Account **
Name: Sunil Narain

** Fill out client info **
Name: N/A
Company: N/A

**Comment by taylorgrahamedb** [comment]
Added snarain to account
