### ISSUE TITLE
Please share the quay.io access with me

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/edb-k8s-doc#47]
**If user has Quay.io account please provide username**
username: vibhorkumar123

**If user has no Quay.io account provide email**
Email: vibhor.kumar@enterprisedb.com

** EDB Sales Engineer for Account **
Name: Taylor Graham 

** Fill out client info **
Name: John Doe 
Company: Enterprise Widgets

**Comment by taylorgrahamedb** [comment]
Done!
