### ISSUE TITLE
Accessto edb-k8s-doc for the Partner of EDB - Adcubum

### ISSUE THREAD

**Issue by borysneselovskyi** [EnterpriseDB/edb-k8s-doc#49]
**If user has no Quay.io account provide email**
Email: christian.pfister@adcubum.com

** EDB Sales Engineer for Account **
Name: Borys Neselovskyi 

** Fill out client info **
Name: Christian Pfister
Company: Adcubum AG

**Comment by borysneselovskyi** [comment]
Adcubum AG uses Kubernetes Operation and OpenShift Integration for the own J2EE Application Syrius and is interested to test our k8s solution for the Postgres Database

**Comment by taylorgrahamedb** [comment]
You should see a email in your inbox from Quay for access! Thank you! 

TG

**Comment by borysneselovskyi** [comment]
Thanks! The Customer was able to access sources...

Kind regards / mit freundlichem Grüßen

Borys Neselovskyi
Regional Sales Engineer DACH






M: +49 151 68819789
edbpostgres.com <http://edbpostgres.com/>





  Oracle ACE Alumni 

EDB, Anthony Fokkerweg 1, 1059 CM Amsterdam, Netherlands
