### ISSUE TITLE
FIS Global requests access

### ISSUE THREAD

**Issue by trgegs** [EnterpriseDB/edb-k8s-doc#50]
**If user has Quay.io account please provide username**
username: N/A

**If user has no Quay.io account provide email**
Email: Thomas.Schurins@fisglobal.com

** EDB Sales Engineer for Account **
Name: Gaby Schilders

** Fill out client info **
Name: Thomas Schurins
Company: FIS (Global)

**Comment by taylorgrahamedb** [comment]
Hi, added Thomas.Schurins@fisglobal.com EDB quay.io. You should see a email from Quay.io for access. 

TG
