### ISSUE TITLE
KPN Telecom requests access

### ISSUE THREAD

**Issue by trgegs** [EnterpriseDB/edb-k8s-doc#51]
**If user has Quay.io account please provide username**
username: has account, username unknown.

**If user has no Quay.io account provide email**
Email: rene.schrier@kpn.com
** EDB Sales Engineer for Account **
Name: Gaby Schilders

** Fill out client info **
Name: René Schrier
Company: KPN

**Comment by taylorgrahamedb** [comment]
HI, added rene.schrier@kpn.com to EDB Quay. You should see a email from Quay.io

TG
